import os
import platform

env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

env.Library(os.path.join(LIB_DIR, 'sqlite3'), Glob("sqlite3.c"))
env.Program(os.path.join(BIN_DIR, 'sqlite3'), Glob("shell.c"))

